### ISSUE TITLE
Agenda document links to Meeting document in GO

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#355] opened 2020-03-09 10:21 UTC
In ORI: https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22osi_provincie-utrecht_20190809125121%22%5D&type=%5B%22MediaObject%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F121565

In  GO: https://www.stateninformatie.provincie-utrecht.nl/Vergaderingen/Commissie-Omgevingsvisie/2020/19-februari/19:30

All agendaitem -> document (mediaobject) relations seem to be wrong ORI data

**Comment by jurrian** [comment] 2020-03-10 13:11
Duplicate of #269

**Comment by jurrian** [comment] 2020-03-11 09:56
It looks like the the mentioned example has been solved. There might be some agenda items which still show the wrong attachment because they are currently being processed, should be fixed soon.

**Closed by jurrian** 2020-03-11 09:56 UTC
Labels: bug, duplicate
