### ISSUE TITLE
Index issue prevents sorting by new in groningen

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#373] opened 2020-06-23 12:12 UTC
Replicate:

- [visit](https://openbesluitvorming.nl/search?zoekterm=%22*%22&organisaties=%5B%22ori_groningen_20190809125025%22%5D&datums=%5B949359600000%2C1624449850180%5D)
- click "nieuwste eerst"
- No results
- check network tab:

```
"reason": "The length of [text] field of [2825921] doc of [ori_groningen_20190809125025] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!"
```

**Comment by jurrian** [comment] 2020-06-23 15:30
Document 2825921 contained an exceptionally long PDF extract, apparently this is the first time it occurred. I've deleted this document and updated the mapping so next time it will be indexed with term vectors which should solve the problem. For now the problem is solved.

**Closed by jurrian** 2020-06-23 15:30 UTC
