### ISSUE TITLE
Provincie Utrecht REST items 404

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#332] opened 2020-02-05 11:58 UTC
See [these results in search](https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22osi_provincie-utrecht_20190809125121%22%5D&type=%5B%22Meeting%22%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F120471).

e.g. meetings  https://id.openraadsinformatie.nl/65791 and https://id.openraadsinformatie.nl/65812

Orgs tend to work just fine. Might have to do something with [GO API v1 / v2](https://github.com/openstate/open-raadsinformatie/issues/269)

**Comment by jurrian** [comment] 2020-02-06 10:10
Most probably it's a duplicate of #269. We will try to fix that one and see if the problem is solved.

**Comment by jorritb** [comment] 2020-02-14 09:10
Kafka is still more than 1 million messages behind so I can't say yet whether the reprocess has worked.

**Comment by jorritb** [comment] 2020-02-14 14:34
The two items at the top of this issue are now available, so I  assume that it is working and it is just a matter of the Kafka consumer being delayed.

**Closed by jorritb** 2020-02-14 14:34 UTC
Labels: duplicate
