### ISSUE TITLE
Documents missing/blocked 

### ISSUE THREAD

**Issue by EonDown** [openstate/open-raadsinformatie#480] opened 2024-08-08 16:30 UTC
## Describe the bug
Documents from Gemeente Nieuwkoop are not loading and when following the link it says "The request is blocked."

This doesn't seem to be the case with all municipalities though. It doesn't work for me through https://openbesluitvorming.nl/?zoekterm=%22*%22&organisaties=%5B%22ori_fixed_nieuwkoop_20230706084053%22%5D either if that helps.

**Comment by vanderburgt** [comment] 2024-08-12 09:13
Able to reproduce this for Gemeente Utrecht, which also uses iBabs.
https://api1.ibabs.eu/publicdownload.aspx?site=Utrecht&id=ee0ddc59-bc1f-417a-8dc4-0da025112316

**Comment by joepio** [comment] 2024-08-12 10:02
Reached out to iBabs for help

**Comment by KasSieu** [comment] 2024-08-14 19:10
> It seems iBabs deliberately blocked it. For my project I need to download the document which now is not possible as it seems. I'll try to think of a workaround. Providing a link might be a good workaround for you though, but less then ideal a well.

If you just need one or a few files you can download them quite easy by printing them to PDF, the print function is hidden behind the hamburgerbutton. Or just contact the griffie of Nieuwkoop they should be able to help you.

> Reached out to iBabs for help

As you can see I've also contacted them. In my reply I've asked them if the download function will be turned on or off by default, and if it would be possible for them to link to the site of the municipality if downloads are turned of. Will let you know when i get a reply.

**Comment by joepio** [comment] 2024-08-28 12:04
Nope, just sent another reminder.

**Comment by joepio** [comment] 2024-08-29 11:33
Seems to be working again! I suppose they did fix something at iBabs. Closing for now.

**Closed by joepio** 2024-08-29 11:33 UTC
Labels: bug
